### ISSUE TITLE
Lay out basic program structure.

### ISSUE THREAD

**Issue by Pharaoh439** [Pharaoh439/capstone#11]
Determine how the program will be run. MVC? Or is there a better way?

**Comment by Pharaoh439** [comment]
We should probably talk about this one before actually doing anything. There is a lot of "Software Engineering" stuff that needs doing before we start so we don't waste our time.

**Comment by itsez** [comment]
We discussed how to best layout the MVC pattern into packages and decided on breaking each component into a package and containing them in one project folder with a main app class able to reference the components as needed.
