### ISSUE TITLE
The user should be able to view an object’s properties and status from the viewing window.

### ISSUE THREAD

**Issue by itsez** [Pharaoh439/capstone#17]

**Comment by itsez** [comment]
Focus for when we create status windows. 
http://www.glfw.org/docs/latest/group__window.html#ga873780357abd3f3a081d71a40aae45a1

**Comment by Pharaoh439** [comment]
Implementation of text within the viewing window is a giant task, and one that is not directly beneficial to the rest of the project. As such, we are declaring this to be out of our current scope.
