### ISSUE TITLE
Implement AABBs in order to check collision, and Quadtrees in order to more efficiently store entities.

### ISSUE THREAD

**Issue by Pharaoh439** [Pharaoh439/capstone#18]

**Comment by itsez** [comment]
http://www.java-gaming.org/index.php?action=pastebin&hex=4af3b227b3d1a
Rectangle Quad Tree Implementation

**Comment by itsez** [comment]
Explains B-Trees really well:
https://www.codeproject.com/Articles/1158559/B-Tree-Another-Implementation-By-Java

**Comment by Pharaoh439** [comment]
https://en.wikipedia.org/wiki/Quadtree
Normal Quadtree implementation, not meant for storing bounding boxes but shows structure pretty well

**Comment by Pharaoh439** [comment]
Arraylist works reasonably efficiently for now, but I am worried about the O(n)-ness of it. We will revisit this later to replace it with Quadtree, but it is just a massive time sink right now.
